### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by cannod** [underscoremone/android_device_samsung_gtexswifi#1]
Hi,

I am running your build on my t280 which I found at https://forum.xda-developers.com/galaxy-tab-a/development/rom-samsung-galaxy-tab-7-0-sm-t280-t4158061

Awesome work!

If possible, could you document your build process so I can build the ROM myself.

Thanks

**Comment by underscoremone** [comment]
Done. See [README - Build Instructions](https://github.com/underscoremone/android_device_samsung_gtexswifi/blob/cm-14.1/README.md#build-instructions).
